steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/amazon-crawler:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/amazon-crawler:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'amazon-crawler'
      - '--image=gcr.io/$PROJECT_ID/amazon-crawler:$COMMIT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--allow-unauthenticated'  # Elimina questa riga se desideri richiedere l'autenticazione

images:
  - 'gcr.io/$PROJECT_ID/amazon-crawler:$COMMIT_SHA'

# Timeout esteso per consentire il completamento del build e del deploy
timeout: '1800s'