version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # FastAPI sulla porta 8080
      - "8501:8501"  # Streamlit sulla porta 8501 (per sviluppo locale)
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/amazon_crawler
      - ENVIRONMENT=development
      - DEBUG=true
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=amazon_crawler
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: